services:
  app:
    build:
      context: .
    container_name: app
    healthcheck:
      test:
        - CMD-SHELL
        - python -c 'import os, urllib.request; port=os.getenv("PORT"); print(urllib.request.urlopen(f"http://localhost:{port}/healthcheck").read());'
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 3000:3000
