services:
  app:
    build:
      context: .
    container_name: app
    healthcheck:
      test:
        - CMD-SHELL
        - python -c 'import urllib.request; print(urllib.request.urlopen("http://localhost:3000/healthcheck").read());'
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 3000:3000
