name: Test

on:
 push:
   paths:
     - '**/src'
     - ".github/workflows/test.yml"
 pull_request:
   paths:
     - '**/src'
     - ".github/workflows/test.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest flake8
          pip install -r ./requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

      - name: Analysing the code with flake8
        run: |
          flake8 --ignore E501 $(git ls-files '*.py')

      - name: Running the tests
        run: |
          pytest -v
